### PR TITLE
Fix false negative `NoPhpOpenTagInCodeBlockPhpDirective` rule with comment

### LINKED ISSUE #1343: False negative `NoPhpOpenTagInCodeBlockPhpDirective` rule when first line is a comment
From symfony-docs
https://github.com/symfony/symfony-docs/blob/15465df251c19acff319db5304db7c9471be99e2/components/uid.rst?plain=1#LL129-L132C14

If a php block start with a comment before php open tag, this is not reported as a Violation

### PR DESCRIPTION
**Pull request by MrYamous**
Fixes #1343

### CODE REVIEW

File: src/Rule/NoPhpOpenTagInCodeBlockPhpDirective.php [hunk 1]
```diff
@@ -50,6 +50,11 @@ public function check(Lines $lines, int $number, string $filename): ViolationInt
         // check if next line is "<?php"
         $nextLine = $lines->current();
 
+        if (str_starts_with($nextLine->clean()->toString(), '//')) {
```
Comment (OskarStark) [inline src/Rule/NoPhpOpenTagInCodeBlockPhpDirective.php:53]:
```suggestion
        if ($nextLine->clean()->startsWith('//')) {
```
?

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you
